# Disable sudo to speed up build
sudo:                   false

# Set the build language
language:               generic

# Set build branch
branches:               master

before_install:
    # Configure access token to enable pushing to the repository
    - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Calculator.git

    # Set commit username
    - git config --global user.name "ROS Bot"

    # Set commit email
    - git config --global user.email "richiebendall@gmail.com"

cache:
  # Ensure npm is cached
  directories:
      - node_modules # NPM packages

  install:
      # Install the required dependency
      - npm install workbox-cli --global

  script:
      # Generate service worker cacher
      - workbox generateSW workbox-config.js

      # Check, commit and push
      - git add . && git diff-index --quiet HEAD || git commit -m "CI | Updated Service Worker Caching [skip ci]" && git push origin HEAD:master

  after_script:
      # Clear CloudFlare cache
      - |
        curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
        -H "X-Auth-Email: richiebendall@gmail.com" \
        -H "X-Auth-Key: ${cf_api_key}" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'

notifications:
    # Disable emails for build status notifications
    email:                false
